name: writer
description: A simple text editor application.
publish_to: 'none'
version: 0.1.0+1
homepage: https://expidusos.com
funding:
  - https://opencollective.com/expidusos

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  intl: ^0.18.0
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: f48d528ebfc22fe827fe9f2d1965be1d339ccfb7
      path: packages/libtokyo
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: f48d528ebfc22fe827fe9f2d1965be1d339ccfb7
      path: packages/libtokyo_flutter
  package_info_plus: ^3.1.2
  provider: ^6.0.5
  pub_semver: ^2.1.4
  pubspec: ^2.3.0
  sentry_flutter: ^7.9.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  xml: ^6.3.0
  path_provider: ^2.1.1
  xdg_directories: ^1.0.3
  flutter_adaptive_scaffold: ^0.1.7+1
  path: ^1.8.3
  material_symbols_icons: ^4.2668.0
  mime_type: ^1.0.0
  file_selector: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: f48d528ebfc22fe827fe9f2d1965be1d339ccfb7
      path: packages/libtokyo

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/
    - pubspec.yaml
    - .dart_tool/package_config.json
    - PRIVACY.md
